### ISSUE TITLE
Error when following "Start a new project" guide

### ISSUE THREAD

**Issue by dclausen** [luckyframework/lucky_cli#147] opened 2018-01-05 19:13 UTC
Trying to follow the "Start a new project" guide located here:
https://luckyframework.org/guides/installing/

and getting an error:

```in lib/lucky/src/lucky/action.cr:1: while requiring "./*": can't specify arguments in both, command and args without including "${@}" into your command```

Here's a gist showing the backtrace:
https://gist.github.com/dclausen/e2bba86f38b1d881da17ea74f5a94862

**Comment by paulcsmith** [comment] 2018-01-05 19:23
@dclausen Thanks for reporting the issue. Can you also post what OS and version you are on? Did you install through Homebrew or with git/crystal build instructions?

**Comment by dclausen** [comment] 2018-01-05 19:24
MacOS High Sierra. I installed via Homebrew:

```brew tap luckyframework/homebrew-lucky```
```brew install lucky```

**Comment by paulcsmith** [comment] 2018-01-05 19:40
@dclausen I just tried uninstalling and reinstalling Crystal and Lucky and it seemed to work. Just to rule out any weirdness during install can you try:

* `brew uninstall --force lucky crystal-lang`
* `brew install lucky crystal-lang`

Also what shell are you using?

**Comment by dclausen** [comment] 2018-01-05 19:50
I'm using zsh.

I tried following your commands:

```
➜  my_blog git:(master) ✗ brew uninstall --force lucky crystal-lang
Uninstalling lucky... (3 files, 342.9KB)
Uninstalling crystal-lang... (1,616 files, 105.8MB)
➜  my_blog git:(master) ✗ brew install lucky crystal-lang
==> Installing lucky from luckyframework/lucky
==> Installing dependencies for luckyframework/lucky/lucky: crystal-lang
==> Installing luckyframework/lucky/lucky dependency: crystal-lang
==> Downloading https://homebrew.bintray.com/bottles/crystal-lang-0.24.1_1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring crystal-lang-0.24.1_1.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/crystal-lang/0.24.1_1: 827 files, 47MB
==> Installing luckyframework/lucky/lucky
==> Downloading https://github.com/luckyframework/homebrew-lucky/raw/master/built_binaries/lucky-0.8.3
Already downloaded: /Users/davidclausen 1/Library/Caches/Homebrew/lucky-0.8.3.3
==> mv lucky-0.8.3 lucky
🍺  /usr/local/Cellar/lucky/0.8.3: 3 files, 342.8KB, built in 3 seconds
➜  my_blog git:(master) ✗ lucky -v
Error in tasks.cr:2: while requiring "./src/app"

require "./src/app"
^

in src/app.cr:1: while requiring "./dependencies"

require "./dependencies"
^

in src/dependencies.cr:2: while requiring "lucky"

require "lucky"
^

in lib/lucky/src/lucky.cr:7: while requiring "./lucky/*"

require "./lucky/*"
^

in lib/lucky/src/lucky/action.cr:1: while requiring "./*": can't specify arguments in both, command and args without including "${@}" into your command

require "./*"
^
➜  my_blog git:(master) ✗ which lucky
/usr/local/bin/lucky
➜  my_blog git:(master) ✗ ls -al /usr/local/bin/lucky
lrwxr-xr-x  1 dave  admin  31 Jan  5 14:48 /usr/local/bin/lucky -> ../Cellar/lucky/0.8.3/bin/lucky
➜  my_blog git:(master) ✗
➜  my_blog git:(master) ✗ cd ..
➜  crystal lucky -v
0.8.3
```

**Comment by paulcsmith** [comment] 2018-01-05 19:59
Start a discussion here in case you're curious about it: https://gitter.im/crystal-lang/crystal?at=5a4fd81b5355812e5757d6a0

**Comment by paulcsmith** [comment] 2018-01-05 20:13
@dclausen Ok this appears to be an issue in Crystal with regards to spaces in the path. I'm guessing you are creating the project where there is a space somewhere in the path. The solution in the meantime is to create the project in a directory without any spaces e.g. `~/Desktop/code` or something. LMK if that works

I'll be sure to close this once the issue is fixed in Crystal :)

**Comment by dclausen** [comment] 2018-01-05 20:59
My home directory actually had the space in it (not by choice) from having restored from a backup. I've confirmed that removing the space fixed the issue. Sorry for the headache and thanks for the quick help!

**Comment by paulcsmith** [comment] 2018-07-14 01:33
Should be fixed by https://github.com/crystal-lang/crystal/pull/5543

**Closed by paulcsmith** 2018-07-14 01:33 UTC
Labels: bug
