### ISSUE TITLE
Generate github action CI config

### ISSUE THREAD

**Issue by skojin** [luckyframework/lucky_cli#558] opened 2020-10-07 19:21 UTC
Generate github action config in same way as .travis.yml

If this is a good idea then I can make PR

**Comment by jwoertink** [comment] 2020-10-07 19:33
Duplicate of https://github.com/luckyframework/lucky_cli/issues/533

Also, though I do like the idea, I'm wondering if there's enough people that don't use github 🤔 With travis, you can use bitbucket, or gitlab and be fine, but using github actions means that anyone not using github would be required to setup their own CI.

Maybe what we do is we create a page on the website dedicated to a few different CI "Getting started with Circle CI" or "Using Lucky on Travis CI". That might be good enough that if someone didn't want to use GH actions, they would have a resource to switch it out.

**Comment by skojin** [comment] 2020-10-07 19:39
That's just a file, you can remove it if not need. And I not suggest to remove travis config, you can have both. And if you have config by default, then on first push to github, you get working CI. I think that's cool.

Build good CI config from several blog posts is not easy, it takes time to tests. If we will have default config in base project, then people will have place where to make config better with PR.

**Comment by jwoertink** [comment] 2020-10-07 19:56
If you're going to do a PR for it, I think it will need to detect if it's an API or Browser app so it can optionally install yarn and chromedriver for browser stuff. You can probably use [this project](https://github.com/luckyframework/lucky_cli/blob/master/.github/workflows/ci.yml) to get a lot of that setup.

**Closed** 2020-10-21 20:26 UTC

**Comment by paulcsmith** [comment] 2020-10-21 20:51
This is awesome. Thanks @skojin. We just need to document this somewhere in the guides, but this is so cool to have 🎉
